In [2]:
import pandas as pd
from sklearn import preprocessing 
import numpy as np

In [3]:
csv_file = '6TaipeiObserve.csv'
train_set = pd.read_csv(csv_file)
train_set.head()

,觀測時間,測站氣壓,海平面氣壓,氣溫,露點溫度,相對溼度,風速,風向,最大陣風,最大陣風風向,降水量,降水時數,日照時數,全天空日射量,能見度,紫外線指數,總雲量
0,2010-06-01-01,1008.5,1009.3,21.0,16.4,75,4.5,60,8.2,60,0,0.0,NaN,0.0,NaN,0.0,NaN
1,2010-06-01-02,1008.6,1009.4,20.9,16.8,77,2.6,70,8.0,50,0,0.0,NaN,0.0,8.0,0.0,7.0
2,2010-06-01-03,1008.7,1009.5,20.8,17.1,79,1.6,100,8.3,60,0,0.0,NaN,0.0,NaN,0.0,NaN
3,2010-06-01-04,1008.9,1009.7,19.9,15.6,76,1.6,150,4.4,100,0,0.0,NaN,0.0,NaN,0.0,NaN
4,2010-06-01-05,1009.0,1009.8,19.5,14.5,73,1.7,140,3.8,160,0,0.0,NaN,0.0,12.0,0.0,5.0

In [14]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5760 entries, 0 to 5759
Data columns (total 17 columns):
觀測時間      5760 non-null object
測站氣壓      5760 non-null float64
海平面氣壓     5760 non-null float64
氣溫        5760 non-null float64
露點溫度      5760 non-null float64
相對溼度      5760 non-null int64
風速        5760 non-null float64
風向        5760 non-null object
最大陣風      5760 non-null float64
最大陣風風向    5760 non-null int64
降水量       5376 non-null float64
降水時數      5760 non-null float64
日照時數      3360 non-null float64
全天空日射量    5760 non-null float64
能見度       2189 non-null float64
紫外線指數     5736 non-null float64
總雲量       3380 non-null float64
dtypes: float64(13), int64(2), object(2)
memory usage: 765.1+ KB

In [5]:
train_set.describe()

,測站氣壓,海平面氣壓,氣溫,露點溫度,相對溼度,風速,最大陣風,最大陣風風向,降水時數,日照時數,全天空日射量,能見度,紫外線指數,總雲量
count,5760.000000,5760.00000,5760.000000,5760.000000,5760.000000,5760.000000,5760.000000,5760.000000,5760.000000,3360.000000,5760.000000,2189.000000,5736.000000,3380.000000
mean,1004.777326,1006.51283,28.469028,23.236441,74.163889,1.671962,4.947674,174.399306,0.142552,0.244673,0.585602,14.330471,1.510286,7.868935
std,2.909773,3.05980,3.145629,1.572783,9.985832,1.207360,2.722900,89.967409,0.325583,0.334778,0.893283,7.423720,2.505213,2.351662
min,991.800000,992.50000,19.500000,14.500000,38.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.200000,0.000000,0.000000
25%,1003.000000,1004.80000,26.175000,22.400000,67.000000,0.800000,2.900000,90.000000,0.000000,0.000000,0.000000,10.000000,0.000000,7.000000
50%,1004.900000,1006.80000,28.000000,23.300000,75.000000,1.400000,4.100000,160.000000,0.000000,0.000000,0.000000,13.000000,0.000000,9.000000
75%,1006.700000,1008.70000,30.700000,24.300000,82.000000,2.200000,6.500000,260.000000,0.000000,0.500000,0.972500,18.000000,2.000000,10.000000
max,1012.400000,1015.50000,38.500000,28.300000,99.000000,8.100000,20.600000,360.000000,1.000000,1.000000,3.920000,70.000000,12.000000,10.000000

In [6]:
def normalization(df, key):
    """Normalize a dataframe with specified columns

    Keyword arguments:
    df -- the input dataframe (pandas.DataFrame)
    cols -- the specified columns to be normalized (list)

    """
    x = df[[key]].values.astype(float)
    min_max_scaler = preprocessing.MinMaxScaler()
    x_scaled = min_max_scaler.fit_transform(x)
    normalized_data = pd.DataFrame(x_scaled)
    normalized_data.columns = [key]
    return normalized_data

In [7]:
normalize_train_set = train_set[['觀測時間']].copy()

In [8]:
keys = ['測站氣壓', '海平面氣壓', '氣溫', '露點溫度', '相對溼度', '風速']
for key in keys:
    temp = normalization(train_set, key)
    normalize_train_set = pd.concat([normalize_train_set, temp], axis=1, sort=False)

In [25]:
#train_set.降水量 = train_set.降水量.convert_objects(convert_numeric=True)
normalize_train_set['降水量'] = np.where(train_set.降水量 > 0.5, 1, 0)

In [24]:
normalize_train_set.loc[normalize_train_set.降水量==1]

,觀測時間,測站氣壓,海平面氣壓,氣溫,露點溫度,相對溼度,風速,降水量
42,2010-06-02-19,0.966019,0.869565,0.052632,0.239130,0.770492,0.493827,1
44,2010-06-02-21,1.000000,0.900000,0.031579,0.217391,0.770492,0.617284,1
45,2010-06-02-22,1.000000,0.900000,0.021053,0.217391,0.786885,0.333333,1
46,2010-06-02-23,0.980583,0.882609,0.015789,0.239130,0.819672,0.370370,1
47,2010-06-02-24,0.946602,0.852174,0.021053,0.268116,0.852459,0.395062,1
48,2010-06-03-01,0.917476,0.826087,0.036842,0.311594,0.885246,0.320988,1
49,2010-06-03-02,0.893204,0.804348,0.063158,0.355072,0.885246,0.222222,1
50,2010-06-03-03,0.878641,0.791304,0.078947,0.376812,0.885246,0.308642,1
51,2010-06-03-04,0.878641,0.791304,0.084211,0.376812,0.885246,0.456790,1
52,2010-06-03-05,0.878641,0.791304,0.094737,0.384058,0.868852,0.469136,1
53,2010-06-03-06,0.898058,0.808696,0.100000,0.405797,0.885246,0.493827,1
54,2010-06-03-07,0.907767,0.817391,0.115789,0.427536,0.885246,0.308642,1
55,2010-06-03-08,0.907767,0.817391,0.131579,0.456522,0.901639,0.395062,1
56,2010-06-03-09,0.907767,0.817391,0.157895,0.485507,0.885246,0.370370,1
57,2010-06-03-10,0.898058,0.808696,0.168421,0.507246,0.901639,0.456790,1
58,2010-06-03-11,0.868932,0.782609,0.189474,0.536232,0.901639,0.296296,1
59,2010-06-03-12,0.854369,0.769565,0.200000,0.528986,0.868852,0.382716,1
60,2010-06-03-13,0.834951,0.752174,0.194737,0.521739,0.868852,0.382716,1
61,2010-06-03-14,0.810680,0.730435,0.189474,0.500000,0.852459,0.580247,1
88,2010-06-04-17,0.776699,0.700000,0.163158,0.434783,0.819672,0.098765,1
89,2010-06-04-18,0.796117,0.717391,0.152632,0.449275,0.852459,0.037037,1
90,2010-06-04-19,0.810680,0.730435,0.142105,0.449275,0.868852,0.037037,1
105,2010-06-05-10,0.854369,0.769565,0.157895,0.485507,0.885246,0.111111,1
106,2010-06-05-11,0.834951,0.752174,0.173684,0.500000,0.885246,0.111111,1
231,2010-06-10-16,0.718447,0.643478,0.310526,0.601449,0.786885,0.691358,1
232,2010-06-10-17,0.742718,0.665217,0.305263,0.652174,0.852459,0.111111,1
233,2010-06-10-18,0.742718,0.665217,0.284211,0.652174,0.885246,0.185185,1
234,2010-06-10-19,0.747573,0.669565,0.294737,0.644928,0.852459,0.234568,1
236,2010-06-10-21,0.786408,0.704348,0.294737,0.688406,0.918033,0.000000,1
237,2010-06-10-22,0.796117,0.713043,0.289474,0.659420,0.885246,0.160494,1
...,...,...,...,...,...,...,...,...
5415,2017-06-16-16,0.475728,0.547826,0.236842,0.543478,0.836066,0.320988,1
5416,2017-06-16-17,0.480583,0.552174,0.242105,0.557971,0.836066,0.172840,1
5417,2017-06-16-18,0.475728,0.547826,0.263158,0.572464,0.819672,0.037037,1
5424,2017-06-17-01,0.432039,0.508696,0.226316,0.557971,0.868852,0.037037,1
5427,2017-06-17-04,0.407767,0.486957,0.226316,0.572464,0.885246,0.111111,1
5431,2017-06-17-08,0.432039,0.508696,0.257895,0.594203,0.852459,0.037037,1
5432,2017-06-17-09,0.466019,0.539130,0.273684,0.594203,0.836066,0.172840,1
5435,2017-06-17-12,0.490291,0.560870,0.263158,0.608696,0.868852,0.246914,1
5436,2017-06-17-13,0.475728,0.547826,0.205263,0.478261,0.803279,0.456790,1
5437,2017-06-17-14,0.485437,0.556522,0.189474,0.456522,0.803279,0.456790,1
5438,2017-06-17-15,0.485437,0.556522,0.184211,0.456522,0.803279,0.444444,1
5439,2017-06-17-16,0.500000,0.569565,0.178947,0.471014,0.836066,0.333333,1
5440,2017-06-17-17,0.538835,0.604348,0.178947,0.478261,0.852459,0.197531,1
5441,2017-06-17-18,0.543689,0.608696,0.152632,0.427536,0.819672,0.234568,1
5442,2017-06-17-19,0.563107,0.626087,0.157895,0.434783,0.819672,0.283951,1
5443,2017-06-17-20,0.597087,0.656522,0.152632,0.434783,0.836066,0.234568,1
5444,2017-06-17-21,0.606796,0.665217,0.157895,0.434783,0.819672,0.382716,1
5445,2017-06-17-22,0.660194,0.713043,0.147368,0.427536,0.836066,0.197531,1
5446,2017-06-17-23,0.616505,0.673913,0.157895,0.442029,0.836066,0.246914,1
5453,2017-06-18-06,0.572816,0.634783,0.184211,0.456522,0.803279,0.345679,1
5454,2017-06-18-07,0.601942,0.660870,0.189474,0.478261,0.836066,0.222222,1
5455,2017-06-18-08,0.587379,0.647826,0.205263,0.507246,0.836066,0.345679,1
5459,2017-06-18-12,0.538835,0.604348,0.315789,0.630435,0.803279,0.333333,1
5463,2017-06-18-16,0.509709,0.578261,0.294737,0.630435,0.836066,0.098765,1
5464,2017-06-18-17,0.524272,0.591304,0.278947,0.630435,0.868852,0.098765,1
5465,2017-06-18-18,0.563107,0.626087,0.268421,0.608696,0.852459,0.024691,1
5466,2017-06-18-19,0.543689,0.608696,0.226316,0.521739,0.819672,0.111111,1
5477,2017-06-19-06,0.567961,0.630435,0.231579,0.579710,0.885246,0.061728,1
5750,2017-06-30-15,0.631068,0.682609,0.521053,0.623188,0.508197,0.308642,1
5751,2017-06-30-16,0.631068,0.686957,0.394737,0.630435,0.688525,0.148148,1